name: "Deploy codigofacilito"

on: 
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
     - run: echo "Hacemos pull del codigo"
     - run: echo "Correr migraciones"
     - run: echo "Generar binario"
     - run: echo "Publicar version"

  deploy2-codigofacilito:
    needs: deploy-codigofacilito
    runs-on: ubuntu-latest
    steps:
     -run: echo "Hola Job2"
